[package]
name = "Backend"
version = "0.1.0"
authors = ["Lorenzo Tanganelli <56673997+LorenzoTanga-bot@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.7"
